# Generated by Django 5.0.1 on 2024-01-15 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "Ccode",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("Pw", models.CharField(blank=True, max_length=30, null=True)),
                ("Call", models.CharField(blank=True, max_length=20, null=True)),
                ("Add", models.CharField(blank=True, max_length=50, null=True)),
                ("Cname", models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "User",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("Pw", models.CharField(max_length=30)),
                ("Name", models.CharField(max_length=20)),
                ("Hp", models.CharField(blank=True, max_length=20, null=True)),
                ("Ccode", models.IntegerField()),
                ("Level", models.CharField(blank=True, max_length=10, null=True)),
                ("Count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "membership",
            },
        ),
        migrations.CreateModel(
            name="Dividend",
            fields=[
                (
                    "Workcode",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("Adate", models.CharField(blank=True, max_length=10, null=True)),
                ("Cdate", models.CharField(blank=True, max_length=10, null=True)),
                ("Saveurl", models.CharField(blank=True, max_length=50, null=True)),
                ("Worker", models.CharField(blank=True, max_length=20, null=True)),
                ("state", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "User",
                    models.ForeignKey(
                        db_column="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solar_app.membership",
                    ),
                ),
            ],
            options={
                "db_table": "dividend",
            },
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                ("Bunho", models.AutoField(primary_key=True, serialize=False)),
                ("Ccode", models.IntegerField()),
                ("User", models.CharField(max_length=20)),
                ("Add", models.CharField(blank=True, max_length=50, null=True)),
                ("Imgurl", models.CharField(blank=True, max_length=50, null=True)),
                ("Title", models.CharField(blank=True, max_length=50, null=True)),
                ("Time", models.DateTimeField(blank=True, null=True)),
                (
                    "Workcode",
                    models.ForeignKey(
                        blank=True,
                        db_column="Workcode",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solar_app.dividend",
                    ),
                ),
            ],
            options={
                "db_table": "register",
            },
        ),
        migrations.AddField(
            model_name="dividend",
            name="Bunho",
            field=models.ForeignKey(
                db_column="Bunho",
                on_delete=django.db.models.deletion.CASCADE,
                to="solar_app.register",
            ),
        ),
    ]
