# Generated by Django 5.0 on 2024-01-15 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solar_app", "0002_alter_membership_ccode_alter_register_ccode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dividend",
            fields=[
                (
                    "Workcode",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("Adate", models.CharField(blank=True, max_length=10, null=True)),
                ("Cdate", models.CharField(blank=True, max_length=10, null=True)),
                ("Saveurl", models.CharField(blank=True, max_length=50, null=True)),
                ("Worker", models.CharField(blank=True, max_length=20, null=True)),
                ("state", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "Bunho",
                    models.ForeignKey(
                        db_column="Bunho",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="solar_app.register",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        db_column="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solar_app.membership",
                    ),
                ),
            ],
            options={
                "db_table": "dividend",
            },
        ),
    ]
